const nationalityFlagMap: Record<string, string> = {
  // Current F1 Nationalities (2024-2025)
  British: "🇬🇧",
  German: "🇩🇪",
  Spanish: "🇪🇸",
  Finnish: "🇫🇮",
  French: "🇫🇷",
  Dutch: "🇳🇱",
  Australian: "🇦🇺",
  Canadian: "🇨🇦",
  Mexican: "🇲🇽",
  Monégasque: "🇲🇨",
  Japanese: "🇯🇵",
  Danish: "🇩🇰",
  Thai: "🇹🇭",
  Chinese: "🇨🇳",
  American: "🇺🇸",

  // Historical F1 Nationalities
  Brazilian: "🇧🇷",
  Italian: "🇮🇹",
  Austrian: "🇦🇹",
  Belgian: "🇧🇪",
  Polish: "🇵🇱",
  Swedish: "🇸🇪",
  Swiss: "🇨🇭",
  Russian: "🇷🇺",
  Colombian: "🇨🇴",
  Venezuelan: "🇻🇪",
  Indian: "🇮🇳",
  "New Zealander": "🇳🇿",
  Argentine: "🇦🇷",
  Argentinian: "🇦🇷",
  Irish: "🇮🇪",
  Portuguese: "🇵🇹",
  South_African: "🇿🇦",
  "South African": "🇿🇦",

  // Additional F1 Historical Nationalities
  Malaysian: "🇲🇾",
  Indonesian: "🇮🇩",
  Chilean: "🇨🇱",
  Uruguayan: "🇺🇾",
  East_German: "🇩🇪",
  "East German": "🇩🇪",
  Czechoslovak: "🇨🇿",
  Czech: "🇨🇿",
  Hungarian: "🇭🇺",
  Rhodesian: "🇿🇼",
  Zimbabwean: "🇿🇼",
  Liechtensteiner: "🇱🇮",
  Liechtenstein: "🇱🇮",

  // Other Motorsport Nationalities
  Norwegian: "🇳🇴",
  Estonian: "🇪🇪",
  Latvian: "🇱🇻",
  Lithuanian: "🇱🇹",
  Romanian: "🇷🇴",
  Bulgarian: "🇧🇬",
  Croatian: "🇭🇷",
  Serbian: "🇷🇸",
  Slovenian: "🇸🇮",
  Slovak: "🇸🇰",
  Greek: "🇬🇷",
  Turkish: "🇹🇷",
  Ukrainian: "🇺🇦",
  Belarusian: "🇧🇾",
  Moroccan: "🇲🇦",
  Egyptian: "🇪🇬",
  Algerian: "🇩🇿",
  Tunisian: "🇹🇳",
  "South Korean": "🇰🇷",
  Korean: "🇰🇷",
  Singaporean: "🇸🇬",
  Filipino: "🇵🇭",
  Vietnamese: "🇻🇳",
  Taiwanese: "🇹🇼",
  "Hong Konger": "🇭🇰",
  "Hong Kong": "🇭🇰",
  Israeli: "🇮🇱",
  Saudi: "🇸🇦",
  "Saudi Arabian": "🇸🇦",
  Emirati: "🇦🇪",
  Kuwaiti: "🇰🇼",
  Qatari: "🇶🇦",
  Bahraini: "🇧🇭",
  Peruvian: "🇵🇪",
  Ecuadorian: "🇪🇨",
  Paraguayan: "🇵🇾",
  Bolivian: "🇧🇴",
  Panamanian: "🇵🇦",
  "Costa Rican": "🇨🇷",
  Guatemalan: "🇬🇹",
  Salvadoran: "🇸🇻",
  Honduran: "🇭🇳",
  Nicaraguan: "🇳🇮",
  Cuban: "🇨🇺",
  Jamaican: "🇯🇲",
  "Puerto Rican": "🇵🇷",
  Barbadian: "🇧🇧",
  Trinidadian: "🇹🇹",
};

export const getNationalityFlag = (nationality: string): string => {
  return nationalityFlagMap[nationality] || "🏁";
};
